// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfN_wtWY0hLwZ4MqKpC12F6QFcRvC3I3Y',
    appId: '1:406771243329:web:a61b9b47965a51fb44e9c0',
    messagingSenderId: '406771243329',
    projectId: 'robohand-8c86e',
    authDomain: 'robohand-8c86e.firebaseapp.com',
    databaseURL: 'https://robohand-8c86e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'robohand-8c86e.appspot.com',
    measurementId: 'G-JP8VK281DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm-O8tSP_NEr67pOB4SwXgzeHugkfzxrk',
    appId: '1:406771243329:android:dadcf1ca3e5b3eaa44e9c0',
    messagingSenderId: '406771243329',
    projectId: 'robohand-8c86e',
    databaseURL: 'https://robohand-8c86e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'robohand-8c86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV33p7nG5xjz_RbfP6PvoEcwpG16LXmxU',
    appId: '1:406771243329:ios:c4c19f45d6586d1b44e9c0',
    messagingSenderId: '406771243329',
    projectId: 'robohand-8c86e',
    databaseURL: 'https://robohand-8c86e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'robohand-8c86e.appspot.com',
    iosClientId: '406771243329-b07c8i8r8a1cj9ngii195ge1uc5pc792.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );
}
